"---
title: "CooK_Paper2022"
author: "massainesousa"
date: "2022-06-08"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
"Cook15_KNN"
## ASD
```{r}
library(gt)
library(plyr)
library(ggplot2)
library(tidyverse)
library(gridExtra)

time_mod <- c("ASD_Mashed_Cook15_KNN","ASD_Mashed_Cook20_KNN","ASD_Mashed_Cook25_KNN",
              "ASD_Mashed_Cook30_KNN","ASD_Mashed_Cook40_KNN","ASD_Mashed_Cook15_PLS",
              "ASD_Mashed_Cook20_PLS","ASD_Mashed_Cook25_PLS","ASD_Mashed_Cook25_PLS",
              "ASD_Mashed_Cook30_PLS",
              "ASD_Mashed_Cook15_SVM","ASD_Mashed_Cook20_SVM","ASD_Mashed_Cook25_SVM",
              "ASD_Mashed_Cook30_SVM","ASD_Mashed_Cook40_SVM","BUCCHI_Mashed_Cook15_KNN",
              "BUCCHI_Mashed_Cook20_KNN","BUCCHI_Mashed_Cook25_KNN","BUCCHI_Mashed_Cook30_KNN",
              "BUCCHI_Mashed_Cook40_KNN","BUCCHI_Mashed_Cook15_PLS","BUCCHI_Mashed_Cook20_PLS",
              "BUCCHI_Mashed_Cook25_PLS","BUCCHI_Mashed_Cook30_PLS","BUCCHI_Mashed_Cook40_PLS",
              "BUCCHI_Mashed_Cook15_SVM","BUCCHI_Mashed_Cook20_SVM","BUCCHI_Mashed_Cook25_SVM",
              "BUCCHI_Mashed_Cook30_SVM","BUCCHI_Mashed_Cook40_SVM")

time_mod1 <- c("Cook15_KNN","Cook20_KNN","Cook25_KNN","Cook30_KNN","Cook40_KNN",
              "Cook15_PLS","Cook20_PLS","Cook25_PLS","Cook30_PLS","Cook40_PLS",
              "Cook15_SVM","Cook20_SVM","Cook25_SVM","Cook30_SVM","Cook40_SVM",
              "Cook15_KNN","Cook20_KNN","Cook25_KNN","Cook30_KNN","Cook40_KNN",
              "Cook15_PLS","Cook20_PLS","Cook25_PLS","Cook30_PLS","Cook40_PLS",
              "Cook15_SVM","Cook20_SVM","Cook25_SVM","Cook30_SVM","Cook40_SVM")

resCV <- list()
parCM1 <- list()

for (i in 1:length(time_mod)) {
  load(here::here("data",paste("Results_","_Estr2.RData",sep = time_mod[i])))
  
  parCM <- matrix(NA,nrow=10,ncol=13)

    for (j in 1:10) {
      parCM[j,3:13] <- round(t(pCM[[j]]$`CM[[i]]$byClass`),2)
      parCM[j,2] <- time_mod1[i] 
      colnames(parCM) <- c("NIR","Time_mod" ,rownames(pCM[[1]]))
    }
  parCM1[[i]] <- as.data.frame(parCM)
  resCV[[i]] <- resCV_2
}
resCV1 <- do.call(rbind,resCV)
parCM1 <- do.call(rbind,parCM1)
parCM1[1:150,1] <- "ASD"
parCM1[151:nrow(parCM1),1] <- "BUCCHI"
parCM1[,3:ncol(parCM1)] <- sapply(parCM1[,3:ncol(parCM1)], as.numeric)
```

## Tabela resultados CV
```{r}
head(resCV1)
CV1mean <-resCV1%>%group_by(data,model)%>%
  summarise(ROC = mean(ROC, na.rm = T),
            Specificity = mean(Spec, na.rm = T),
            Sensitivity = mean(Sens, na.rm = T)) 
 
CV1mean %>% gt() %>% tab_options(table.font.size = pct(75))

```

## Plots resultados CV
```{r}
resCV1 <- separate(data = resCV1, col = data, into = c("NIR", "trait"), sep = "_")
resCV1$model <- as.factor(resCV1$model)
levels(resCV1$model)[levels(resCV1$model)=='pls'] <- 'PLS'
resCV1$NIR <- as.factor(resCV1$NIR)
resCV1$trait <- as.factor(resCV1$trait)

roc <- ggplot(resCV1, aes(x=model, y=ROC, fill=trait)) + ylab(" ") +
  geom_boxplot(outlier.shape = NA) + theme_bw() + theme(legend.position = "bottom") + ylim(0.6, 1) + ggtitle("ROC - Cross Validation") + facet_grid(.~ NIR)

Sens <- ggplot(resCV1, aes(x=model, y=Sens, fill=trait)) + ylab(" ") +
  geom_boxplot(outlier.shape = NA) + theme_bw() + theme(legend.position = "bottom") + ylim(0.3, 1) + ggtitle("Sensitivity - Cross Validation") + facet_grid(.~ NIR)

Spec <- ggplot(resCV1, aes(x=model, y=Spec, fill=trait)) + ylab(" ") +
  geom_boxplot(outlier.shape = NA) + theme_bw() + theme(legend.position = "bottom") + ylim(0.5, 1) + ggtitle("Specificity - Cross Validation") + facet_grid(.~ NIR)
  #scale_fill_manual(values = c("gray", "olivedrab4","orange3")) ##

library(ggpubr)
tiff(file = "Figura1_CV_binario.tiff", width = 14, height =24, res = 700, compression = "lzw", units = "cm")
 ggarrange(roc,Sens,Spec, nrow=3, common.legend = TRUE, legend="bottom")
 dev.off()

```

## Tabela parametros da CM
```{r}
parCM1mean <-parCM1%>%group_by(NIR,Time_mod)%>%
  summarise(Sensitivity = mean(Sensitivity),
            Specificity=mean(Specificity),
            PosPredValue = mean(`Pos Pred Value`), 
            NegPredValue=mean(`Neg Pred Value`),
            Precision=mean(Precision),
            F1=mean(F1),Recall=mean(Recall),
            Accuracy=mean(`Balanced Accuracy`))
            
parCM1mean %>% gt() %>% tab_options(table.font.size = pct(75))

```

## Plots parametros CV

```{r}
head(parCM1)
parCM1 <- separate(data = parCM1, col = Time_mod, into = c("trait", "model"), sep = "_")
parCM1$model <- as.factor(parCM1$model)
parCM1$NIR <- as.factor(parCM1$NIR)
parCM1$trait <- as.factor(parCM1$trait)

Accuracy <- ggplot(parCM1, aes(x=model, y=`Balanced Accuracy`, fill=trait)) + ylab(" ") +
  geom_boxplot() + theme_bw() + theme(legend.position = "bottom") + ylim(0.6, 1) + ggtitle("Accuracy - Cross Validation") + facet_grid(.~ NIR)

Sens <- ggplot(parCM1, aes(x=model, y=Sensitivity, fill=trait)) + ylab(" ") +
  geom_boxplot() + theme_bw() + theme(legend.position = "bottom") + ylim(0.3, 1) + ggtitle("Sensitivity - Cross Validation") + facet_grid(.~ NIR)

Spec <- ggplot(parCM1, aes(x=model, y=Specificity, fill=trait)) + ylab(" ") +
  geom_boxplot() + theme_bw() + theme(legend.position = "bottom") + ylim(0.5, 1) + ggtitle("Specificity - Cross Validation") + facet_grid(.~ NIR)

tiff(file = "Figura2_CM_binario.tiff", width = 14, height =24, res = 700, compression = "lzw", units = "cm")
 ggarrange(Accuracy,Sens,Spec, nrow=3, common.legend = TRUE, legend="bottom")
 dev.off()

```


### Funcao matrix de confusao
```{r}
prettyConfused<-function(Actual,Predict,colors=c("white","red4","dodgerblue3"),text.scl=5){
  actual = as.data.frame(table(Actual))
  names(actual) = c("Actual","ActualFreq")
  #build confusion matrix
  confusion = as.data.frame(table(Actual, Predict))
  names(confusion) = c("Actual","Predicted","Freq")
  #calculate percentage of test cases based on actual frequency
  confusion = merge(confusion, actual, by=c('Actual','Actual'))
  confusion$Percent = confusion$Freq/confusion$ActualFreq*100
  confusion$ColorScale<-confusion$Percent*-1
  confusion[which(confusion$Actual==confusion$Predicted),]$ColorScale<-confusion[which(confusion$Actual==confusion$Predicted),]$ColorScale*-1
  confusion$Label<-paste(round(confusion$Percent,0),"%, n=",confusion$Freq,sep="")
  tile <- ggplot() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                          panel.background = element_blank(), axis.line = element_blank(),
                          axis.title.x = element_text(size = rel(1)),
                          axis.title.y = element_text(size = rel(1)),
                          axis.text.x = element_text(size=13),axis.text.y = element_text(size=13)) +
    geom_tile(aes(x=Actual, y=Predicted,fill=ColorScale),data=confusion, color="black",size=0.1) +
    labs(x="Reference",y="Predicted")
  
  tile = tile +
    geom_text(aes(x=Actual,y=Predicted, label=Label),data=confusion, size=text.scl, colour="black") +
    scale_fill_gradient2(low=colors[2],high=colors[3],mid=colors[1],midpoint = 0,guide='none')
}

```

## Plot Matriz de confusao (media entre as 10 repeticoes)
```{r}
res <- matrix(NA,nrow = 3,ncol = 10)
pl <- list()
plt <- as.data.frame(tCM[[1]])

for (i in 1:15) {
  load(here::here("data",paste("Results_","_Estr2.RData",sep = time_mod[i])))
 
  for (j in 1:10) {
    res[1,j] <-  tCM[[j]][1,1]
    res[2,j] <-  sum(tCM[[j]][,1])
    res[3,j] <-  tCM[[j]][1,2]
    }
  plt$Freq[1] <- round((mean(res[1,]))*100/mean(res[2,]),1)
  plt$Freq[2] <- 100-plt$Freq[1]
  plt$Freq[3] <- round((mean(res[3,]))*100/mean(res[2,]),1)
  plt$Freq[4] <- 100-plt$Freq[3]
 
pl[[i]] <- ggplot(plt, aes(Prediction,Reference, fill= Freq)) +
        geom_tile() + geom_text(aes(label=Freq)) + labs(title= paste("ASD",time_mod1[i],sep = " ") ) +
        scale_fill_gradient(low="red", high="dodgerblue3") +
       labs(x = "Prediction",y ="Reference" ) +theme_bw() + theme(legend.position = "none",plot.title = element_text(size=10)) 
}

tiff(file = "Figura3_CM_ASD_binario.tiff", width = 26, height =12, res = 700, compression = "lzw", units = "cm")
 do.call(ggarrange, c(pl, nrow = 3,ncol=5) )
dev.off()


res <- matrix(NA,nrow = 3,ncol = 10)
pl <- list()
plt <- as.data.frame(tCM[[1]])

for (i in 1:15) {
  load(here::here("data",paste("Results_","_Estr2.RData",sep = time_mod[15+i])))
 
  for (j in 1:10) {
    res[1,j] <-  tCM[[j]][1,1]
    res[2,j] <-  sum(tCM[[j]][,1])
    res[3,j] <-  tCM[[j]][1,2]
    }
  plt$Freq[1] <- round((mean(res[1,]))*100/mean(res[2,]),1)
  plt$Freq[2] <- 100-plt$Freq[1]
  plt$Freq[3] <- round((mean(res[3,]))*100/mean(res[2,]),1)
  plt$Freq[4] <- 100-plt$Freq[3]
 
pl[[i]] <- ggplot(plt, aes(Prediction,Reference, fill= Freq)) +
        geom_tile() + geom_text(aes(label=Freq)) + labs(title= paste("BUCCHI",time_mod1[i],sep = " ") ) +
        scale_fill_gradient(low="white", high="dodgerblue3") +
       labs(x = "Prediction",y ="Reference" ) +theme_bw() + theme(legend.position = "none",plot.title = element_text(size=10)) }

tiff(file = "Figura4_CM_BUCCHI_binario.tiff", width = 26, height =12, res = 700, compression = "lzw", units = "cm")
 do.call(ggarrange, c(pl, nrow = 3,ncol=5) )
dev.off()
```


